import assert from 'node:assert/strict';
import {readFile,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {generateKeyPairSync,createHash} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const root=new URL('../',import.meta.url),temp=await mkdtemp(join(tmpdir(),'doin-team-e2e-')),checks=[],transcript=[];
const pass=name=>{checks.push(name);console.log(`PASS ${name}`);};
const {privateKey,publicKey}=generateKeyPairSync('ed25519'),pub=publicKey.export({format:'jwk'}),priv=privateKey.export({format:'jwk'});
const customers=new Map(),subs=new Map(),sessions=new Map(),mail=[],operations=new Map(),cached=new Map();let paymentFails=false,providerFails=false;let customerNumber=0,stripeRequests=0;
const portals=[];let portalUrl=null;
const outbound=async request=>{
 const u=new URL(request.url),fields=new URLSearchParams(await request.text());
 if(u.hostname==='mail.fixture'){mail.push(JSON.parse(fields.size?await Promise.resolve('null'):'null'));return Response.json({ok:true});}
 if(u.hostname!=='api.stripe.com')throw new Error(`unexpected outbound ${u}`);stripeRequests++;if(providerFails)return new Response('unavailable',{status:503});
 const key=request.headers.get('idempotency-key'),p=u.pathname;
 if(p==='/v1/prices/price_team')return Response.json({id:'price_team',active:true,unit_amount:9900,currency:'usd',recurring:{interval:'year',interval_count:1,usage_type:'licensed'}});
 if(p==='/v1/customers'){if(!customers.has(key))customers.set(key,{id:`cus_team${++customerNumber}`});return Response.json(customers.get(key));}
 if(p==='/v1/subscriptions')return Response.json({data:subs.has(u.searchParams.get('customer'))?[subs.get(u.searchParams.get('customer'))]:[],has_more:false});
 if(p==='/v1/billing_portal/sessions'){portals.push(Object.fromEntries(fields));return Response.json({id:`bps_${portals.length}`,customer:fields.get('customer'),url:portalUrl??`https://billing.stripe.com/p/session/team_${portals.length}`});}
 if(p==='/v1/checkout/sessions'){if(!sessions.has(key))sessions.set(key,{id:`cs_team${sessions.size+1}`,customer:fields.get('customer'),status:'open',url:`https://checkout.stripe.com/c/pay/test_team${sessions.size+1}`,seats:Number(fields.get('line_items[0][quantity]')),expires_at:Number(fields.get('expires_at'))});return Response.json(sessions.get(key));}
 if(p.startsWith('/v1/checkout/sessions/')){const s=[...sessions.values()].find(s=>s.id===p.split('/')[4]);assert.ok(s);if(p.endsWith('/expire')){if(s.status!=='open')return new Response('not open',{status:400});s.status='expired';}return Response.json(s);}
 if(p==='/v1/invoices/create_preview')return Response.json({currency:'usd',amount_due:5000});
 if(p.startsWith('/v1/subscriptions/')){const s=[...subs.values()].find(s=>s.id===p.split('/')[3]);assert.ok(s);if(key&&cached.has(key))return Response.json(cached.get(key));if(request.method==='DELETE')s.status='canceled';else if(fields.has('cancel_at_period_end'))s.cancel_at_period_end=fields.get('cancel_at_period_end')==='true';else if(!operations.has(key)){operations.set(key,Object.fromEntries(fields));if(paymentFails)s.pending_update={expires_at:Math.floor(Date.now()/1000)+3600};else{s.items.data[0].quantity=Number(fields.get('items[0][quantity]'));s.pending_update=null;}}if(key)cached.set(key,structuredClone(s));return Response.json(s);}
 throw new Error(`unexpected Stripe ${request.method} ${p}`);
};
 const source=`import {teamRoute,teamAccountDeletionGuard} from '${root.pathname}team.ts';import {verifyLicense,issueLicense} from '${root.pathname}license.ts';import {documentWrite} from '${root.pathname}folders.ts';export default {async fetch(r,env){try{const u=new URL(r.url);if(u.pathname==='/__config'){globalThis.__config=await r.json();return Response.json({ok:true});}if(globalThis.__config)Object.assign(env,globalThis.__config);if(u.pathname==='/__issue_live'){return Response.json(await issueLicense({...env,STRIPE_SECRET_KEY:'sk_live_fixture'},await r.json()));}if(u.pathname==='/__verify'){const d=await r.json();try{return Response.json(await verifyLicense(d.receipt,JSON.parse(env.LICENSE_PUBLIC_KEY),env.LICENSE_KEY_ID,d.expected,d.time));}catch{return Response.json({error:'invalid_license'},{status:400});}} const id=r.headers.get('x-actor');const actor=await env.DB.prepare('SELECT id,email,closing_at FROM accounts WHERE id=?').bind(id).first();if(!actor)return new Response('auth',{status:401});if(u.pathname==='/__assignment_race'){const d=await r.json();const proxy={prepare(sql){const statement=env.DB.prepare(sql);return {bind(...args){const bound=statement.bind(...args);return {async first(){if(sql.includes('UPDATE team_folders SET content=')){if(d.expire)await env.DB.prepare('UPDATE teams SET period_end=0 WHERE id=?').bind(d.team_id).run();else await env.DB.prepare('DELETE FROM team_folder_grants WHERE team_id=? AND folder_id=? AND account_id=?').bind(d.team_id,d.folder_id,d.assignee).run();}return bound.first();}};}};}};return Response.json(await documentWrite({DB:proxy},d.team_id,id,d.folder_id,d.revision,d.content));}if(u.pathname==='/__delete_account'){await teamAccountDeletionGuard(env,id);await env.DB.prepare('DELETE FROM accounts WHERE id=?').bind(id).run();return Response.json({deleted:true});}return await teamRoute(r,env,actor,{body:async(r,max=8192)=>{const raw=await r.text();if(new TextEncoder().encode(raw).length>max)throw Response.json({error:'too_large'},{status:413});return JSON.parse(raw);},emailAddress:v=>{if(typeof v!=='string'||!v.includes('@'))throw Response.json({error:'email'},{status:400});return v.toLowerCase();}});}catch(e){if(e instanceof Response)return e;console.error(e);return Response.json({error:'internal'},{status:500});}}};`;
await build({stdin:{contents:source,loader:'ts',resolveDir:root.pathname},outfile:join(temp,'worker.mjs'),bundle:true,format:'esm',platform:'browser'});
const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'team-e2e',modules:true,script:await readFile(join(temp,'worker.mjs'),'utf8'),compatibilityDate:'2026-10-01',d1Databases:['DB'],bindings:{ORIGIN:'https://sync.doin.sh',EMAIL_FROM:'login@doin.sh',STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_PRICE_ID:'price_month',STRIPE_TEAM_PRICE_ID:'price_team',LICENSE_SIGNING_KEY:JSON.stringify(priv),LICENSE_PUBLIC_KEY:JSON.stringify(pub),LICENSE_KEY_ID:'e2e-key'},serviceBindings:{EMAIL:{name:'mail',entrypoint:'Mailer'}},outboundService:outbound},{name:'mail',modules:true,compatibilityDate:'2026-10-01',script:`import {WorkerEntrypoint} from 'cloudflare:workers';export class Mailer extends WorkerEntrypoint{async send(m){return fetch('https://mail.fixture/message',{method:'POST',body:JSON.stringify(m)}).then(r=>r.json());}}export default{fetch(){return new Response('404',{status:404})}};`,outboundService:async r=>{mail.push(await r.json());return Response.json({ok:true});}}]}));
async function req(actor,path,method='GET',data,expected=200){const r=await mf.dispatchFetch(`https://sync.doin.sh${path}`,{method,headers:{'x-actor':actor,'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await r.json();transcript.push({actor,path,method,status:r.status,result:result.receipt?{...result,receipt:'[signed receipt]'}:result});assert.equal(r.status,expected,JSON.stringify(result));return result;}
const activate=checkout=>{checkout.status='complete';subs.set(checkout.customer,{id:`sub_${checkout.customer}`,customer:checkout.customer,status:'active',cancel_at_period_end:false,pending_update:null,items:{data:[{id:`si_${checkout.customer}`,price:{id:'price_team'},quantity:checkout.seats,current_period_end:Math.floor(Date.now()/1000)+31536000}]}});};
try{
 const db=await mf.getD1Database('DB');for(const migration of ['0001.sql','0002.sql','0003.sql','0004.sql','0005.sql','0006.sql','0007.sql'])await db.exec((await readFile(new URL(`migrations/${migration}`,root),'utf8')).replaceAll('\n',' '));
 for(const [id,email] of [['owner','owner@example.test'],['admin','admin@example.test'],['member','member@example.test'],['other','other@example.test'],['other2','other2@example.test']])await db.prepare('INSERT INTO accounts(id,identity_key,email,name,created_at) VALUES(?,?,?,?,?)').bind(id,id,email,id,Date.now()/1000).run();
 const terms=await req('owner','/v1/teams/terms');assert.equal(terms.amount,9900);
 await req('owner','/v1/teams','POST',{name:'Wrong',legal_entity:'Wrong LLC'},400);
 const team=await req('owner','/v1/teams','POST',{name:'Real team',legal_entity:'Example LLC',deployment:'self_hosted',accepted_terms:terms.version},201),base=`/v1/teams/${team.id}`;
 await req('owner',base+'/invites','POST',{email:'admin@example.test',role:'admin',ack_admin_global:true,folder_id:'root',folder_access:'write'},402);
 const checkout=await req('owner',base+'/checkout','POST',{seats:3,accepted_terms:terms.version});const again=await req('owner',base+'/checkout','POST',{seats:3,accepted_terms:terms.version});assert.equal(checkout.url,again.url);assert.equal(sessions.size,1);activate([...sessions.values()][0]);
 await db.prepare('UPDATE accounts SET customer_id=? WHERE id=?').bind('cus_personal_owner','owner').run();
 subs.set('cus_personal_owner',{id:'sub_personal_owner',customer:'cus_personal_owner',status:'active',cancel_at_period_end:false,latest_invoice:'in_personal_owner',pending_update:null,items:{data:[{id:'si_personal_owner',price:{id:'price_month'},quantity:1,current_period_end:Math.floor(Date.now()/1000)+86400}]}});
 await req('other','/v1/teams','POST',{name:'Other tenant',legal_entity:'Other LLC',accepted_terms:terms.version},201);await req('other',base+'/members','GET',undefined,404);
 await req('owner',base+'/invites','POST',{email:'admin@example.test',role:'admin',ack_admin_global:true,folder_id:'root',folder_access:'write'});const adminToken=mail.at(-1).text.match(/\n([a-f0-9]{64})\n/)[1];await req('member','/v1/teams/accept','POST',{token:adminToken},404);await req('admin','/v1/teams/accept','POST',{token:adminToken});await req('admin','/v1/teams/accept','POST',{token:adminToken},404);
 await req('admin',base+'/invites','POST',{email:'member@example.test',folder_id:'root',folder_access:'write'});const memberToken=mail.at(-1).text.match(/\n([a-f0-9]{64})\n/)[1];await req('member','/v1/teams/accept','POST',{token:memberToken});await req('member',base+'/checkout','POST',{seats:9,accepted_terms:terms.version},403);
 pass('annual checkout idempotency, paid invitations, email binding and tenant isolation');
 const one=await req('member',base+'/document');await req('member',base+'/document','PUT',{revision:one.revision,content:'# Team\n- [ ] First device\n'});await req('admin',base+'/document','PUT',{revision:one.revision,content:'overwrite'},409);const current=await req('admin',base+'/document');await req('admin',base+'/document','PUT',{revision:current.revision,content:current.content+'- [ ] Second device merged\n'});assert.match((await req('member',base+'/document')).content,/First device[\s\S]*Second device/);
 await req('owner',base+'/leave','POST',{},409);await req('owner','/__delete_account','POST',{},409);await req('admin',base+'/members/remove','POST',{account_id:'owner'},409);
 pass('two-device revision conflict, merge and last-owner guards');
 const restricted=await req('owner',base+'/folders','POST',{name:'Restricted',parent_id:'root'},201),restrictedPath=base+'/folders/'+restricted.id;
 const property='00000000000000000000000000000001',task='11111111111111111111111111111111';
 const assigned=(account,identity=task)=>`<!-- doin:properties=[{"id":"${property}","name":"Assignee","kind":"member","options":[]}] -->\n- [ ] Shared assignment <!-- doin:task=${identity} --> <!-- doin:values={"${property}":"${account}"} -->\n`;
 const eligible=await req('owner',restrictedPath+'/members');assert.deepEqual(eligible.members.map(x=>x.account_id).sort(),['admin','member','owner']);
 // Root grants inherit. Revoke root for member, then expose only restricted read access.
 await req('owner',base+'/folders/root/grants','DELETE',{account_id:'member'});
 await req('owner',restrictedPath+'/document','PUT',{revision:0,content:assigned('member')},409);
 await req('owner',restrictedPath+'/grants','POST',{account_id:'member',access:'read'});
 await req('owner',restrictedPath+'/document','PUT',{revision:0,content:assigned('member')});
 await req('member',restrictedPath+'/document','PUT',{revision:1,content:assigned('owner')},404);
 await req('owner',restrictedPath+'/document','PUT',{revision:1,content:assigned('other')},409);
 await req('owner','/__assignment_race','POST',{team_id:team.id,folder_id:restricted.id,assignee:'member',revision:1,content:assigned('member','22222222222222222222222222222222')},409);
 await req('owner',restrictedPath+'/grants','DELETE',{account_id:'member'});
 await req('owner',restrictedPath+'/document','PUT',{revision:1,content:assigned('member')+'\nHistory retained after folder grant departure\n'});
 await req('owner',restrictedPath+'/document','PUT',{revision:2,content:assigned('member','22222222222222222222222222222222')},409);
 await req('owner',restrictedPath+'/document','PUT',{revision:2,content:assigned('member')+assigned('owner')},400);
 await req('owner','/__assignment_race','POST',{team_id:team.id,folder_id:restricted.id,expire:true,revision:2,content:assigned('owner','22222222222222222222222222222222')},409);
 await db.prepare('UPDATE teams SET period_end=? WHERE id=?').bind(Math.floor(Date.now()/1000)+31536000,team.id).run();
 await req('owner',base+'/folders/root/grants','POST',{account_id:'member',access:'write'});
 pass('scoped assignee roster, inaccessible/foreign IDs, read-only changes and former-member stable history');
 const preview=await req('owner',base+'/seats','POST',{seats:4});assert.equal(preview.amount_due,5000);paymentFails=true;await req('owner',base+'/seats','POST',{seats:4,confirm_amount:preview.amount_due,proration_date:preview.proration_date});assert.equal((await req('owner',base+'/billing')).paid_seats,3);await req('owner',base+'/seats','POST',{seats:5},409);paymentFails=false;const s=[...subs.values()][0];s.pending_update=null;s.items.data[0].quantity=4;assert.equal((await req('owner',base+'/billing')).paid_seats,4);
 const teamPortal=await req('owner',base+'/portal','POST',{});assert.equal(teamPortal.url,'https://billing.stripe.com/p/session/team_1');assert.equal(portals[0].customer,'cus_team1');assert.equal(new URL(portals[0].return_url).pathname,'/account');assert.equal(portals[0]['flow_data[type]'],'payment_method_update');
 portalUrl='https://evil.example/portal';await req('owner',base+'/portal','POST',{},503);portalUrl=null;
 await req('member',base+'/portal','POST',{},403);
 await req('member',base+'/personal-renewal/cancel','POST',{confirmation:'cancel personal renewal'},403);
 await req('owner',base+'/personal-renewal/cancel','POST',{confirmation:'wrong'},400);assert.equal(subs.get('cus_personal_owner').cancel_at_period_end,false);
 const endBeforePersonalCancel=subs.get('cus_personal_owner').items.data[0].current_period_end;
 const personalCancel=await req('owner',base+'/personal-renewal/cancel','POST',{confirmation:'cancel personal renewal'});assert.equal(personalCancel.cancel_at_period_end,true);assert.equal(personalCancel.status,'active');assert.equal(subs.get('cus_personal_owner').cancel_at_period_end,true);assert.equal(subs.get('cus_personal_owner').items.data[0].current_period_end,endBeforePersonalCancel);
 await req('owner',base+'/personal-renewal/cancel','POST',{confirmation:'cancel personal renewal'});assert.equal(subs.get('cus_personal_owner').status,'active');
 const reduction=await req('owner',base+'/seats','POST',{seats:3});assert.equal(reduction.no_refund,true);await req('owner',base+'/seats','POST',{seats:3,confirm_renewal_reduction:true});const billing=await req('owner',base+'/billing');assert.equal(billing.paid_seats,4);assert.equal(billing.next_renewal_seats,3);await req('owner',base+'/seats','POST',{seats:2},409);await req('owner',base+'/seats','POST',{seats:5},409);const restore=await req('owner',base+'/seats','POST',{seats:4});assert.equal(restore.restoring_paid_capacity,true);await req('owner',base+'/seats','POST',{seats:4,confirm_renewal_reduction:true});assert.equal([...operations.values()].at(-1).proration_behavior,'none');await req('owner',base+'/seats','POST',{seats:3,confirm_renewal_reduction:true});
 pass('failed seat payment, reconciliation and reusable paid seats with lower renewal quantity');
 const receipt=await req('owner',base+'/receipt');const expected={environment:'test',entity:'Example LLC',team_id:team.id};await req('owner','/__verify','POST',{receipt:receipt.receipt,expected});await req('owner','/__verify','POST',{receipt:receipt.receipt,expected:{...expected,environment:'live'}},400);await req('owner','/__verify','POST',{receipt:receipt.receipt.replace('doin-license-v1.','doin-license-v1.X'),expected},400);await req('owner','/__verify','POST',{receipt:receipt.receipt,expected,time:receipt.expires_at+1},400);
 pass('signed offline receipt rejects tampering, expiry and sandbox commercial activation');
 await req('owner',base+'/invites','POST',{email:'member@example.test',folder_id:'root',folder_access:'write'});const departedToken=mail.at(-1).text.match(/\n([a-f0-9]{64})\n/)[1];
 await db.prepare('INSERT INTO mcp_auth_grants(id,account_id,client_id,redirect_uri,scopes,created_at,team_id,folder_id) VALUES(?,?,?,?,?,?,?,?)').bind('member-grant','member','client-fixture','https://client.example.test/callback','tasks:read',Math.floor(Date.now()/1000),team.id,'root').run();
 await req('owner',base+'/members/remove','POST',{account_id:'member'});assert.ok((await db.prepare("SELECT revoked_at FROM mcp_auth_grants WHERE id='member-grant'").first()).revoked_at);await req('member','/v1/teams/accept','POST',{token:departedToken},404);await req('member',base+'/export','GET',undefined,404);await req('member',base+'/document','PUT',{revision:2,content:'offline departure'},404);await req('owner',restrictedPath+'/document','PUT',{revision:2,content:assigned('member')+'\nFormer member history preserved\n'});await req('owner',restrictedPath+'/document','PUT',{revision:3,content:assigned('member','33333333333333333333333333333333')},409);
 const raced=[];for(const actor of ['other','other2']){await req('owner',base+'/invites','POST',{email:`${actor}@example.test`});raced.push({actor,token:mail.at(-1).text.match(/\n([a-f0-9]{64})\n/)[1]});}
 const results=await Promise.all(raced.map(async flow=>{const r=await mf.dispatchFetch('https://sync.doin.sh/v1/teams/accept',{method:'POST',headers:{'x-actor':flow.actor,'content-type':'application/json'},body:JSON.stringify({token:flow.token})});return {status:r.status,result:await r.json()};}));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);transcript.push({scenario:'last-seat-race',results});
 pass('concurrent invitation claims cannot exceed renewal seat capacity');
 await req('owner',base+'/transfer','POST',{account_id:'admin'});await req('owner',base+'/cancel','POST',{},403);await req('admin',base+'/cancel','POST',{});await req('admin',base+'/resume','POST',{});await req('admin',base+'/cancel','POST',{});assert.equal((await req('admin',base+'/billing')).cancel_at_period_end,true);await req('admin',base+'/resume','POST',{});assert.equal((await req('admin',base+'/billing')).cancel_at_period_end,false);providerFails=true;await req('owner',base+'/document','PUT',{revision:2,content:'provider outage'},503);providerFails=false;
 await req('admin',base,'DELETE');await req('owner',base+'/export','GET',undefined,404);await req('admin','/__delete_account','POST',{});
 pass('offboarding, owner transfer, cancellation, outage and team deletion preserve boundaries');
 await req('owner','/__config','POST',{SELF_HOST_MODE:'personal'});await req('owner','/v1/teams','GET',undefined,402);
 await req('owner','/__config','POST',{SELF_HOST_MODE:'commercial',SELF_HOST_OWNER_EMAIL:'owner@example.test',COMMERCIAL_LICENSE_RECEIPT:receipt.receipt});await req('owner','/v1/teams','POST',{name:'Local',legal_entity:'Example LLC',accepted_terms:terms.version},402);
 const commercial=await req('owner','/__issue_live','POST',{team_id:'licensed-team',legal_entity:'Self Host LLC',seats:2,expires_at:Math.floor(Date.now()/1000)+3600});
 await req('owner','/__config','POST',{SELF_HOST_MODE:'commercial',SELF_HOST_OWNER_EMAIL:'owner@example.test',COMMERCIAL_LICENSE_RECEIPT:commercial.receipt});
 await req('member','/v1/teams','POST',{name:'Hijack',legal_entity:'Self Host LLC',accepted_terms:terms.version},403);await req('owner','/v1/teams','POST',{name:'Wrong entity',legal_entity:'Wrong LLC',accepted_terms:terms.version},400);
 const beforeStripe=stripeRequests;const local=await req('owner','/v1/teams','POST',{name:'Local',legal_entity:'Self Host LLC',accepted_terms:terms.version},201);assert.equal(local.id,'licensed-team');assert.equal(local.deployment,'self_hosted');const localBase='/v1/teams/licensed-team';
 providerFails=true;assert.equal((await req('owner',localBase+'/billing')).paid_seats,2);await req('owner',localBase+'/invites','POST',{email:'member@example.test',folder_id:'root',folder_access:'write'});const localToken=mail.at(-1).text.match(/\n([a-f0-9]{64})\n/)[1];await req('member','/v1/teams/accept','POST',{token:localToken});await req('member',localBase+'/document','PUT',{revision:0,content:'Self-hosted commercial data'});await req('owner',localBase+'/checkout','POST',{seats:4,accepted_terms:terms.version},409);assert.equal(stripeRequests,beforeStripe);providerFails=false;
 pass('commercial self-hosting enforces signed live receipt, entity, fixed team, configured owner and seats without Stripe');

 // Exercise the actual exported Worker, including its session and personal billing boundary.
 let actualWorkerSource=await readFile(new URL('worker.ts',root),'utf8');actualWorkerSource=actualWorkerSource.replace('const url = new URL(request.url), path = url.pathname;','const url = new URL(request.url), path = url.pathname; if(path==="/__config"){globalThis.__actualConfig=await request.json();Object.assign(env,globalThis.__actualConfig);return json({ok:true});} if(globalThis.__actualConfig)Object.assign(env,globalThis.__actualConfig);');
 await build({stdin:{contents:actualWorkerSource,loader:'ts',resolveDir:root.pathname},outfile:join(temp,'actual-worker.mjs'),external:['cloudflare:workers'],bundle:true,format:'esm',platform:'browser'});
 let actualStripe=0,actualHosted=false;const actualSubscriptions=new Map(),actualPortals=[];const actual=new Miniflare(convertV4MiniflareOptions({workers:[{name:'personal-selfhost',modules:true,script:await readFile(join(temp,'actual-worker.mjs'),'utf8'),compatibilityDate:'2026-10-01',d1Databases:['DB'],kvNamespaces:['OAUTH_KV'],bindings:{ORIGIN:'https://personal.example.test',SELF_HOST_MODE:'personal',SELF_HOST_OWNER_EMAIL:'owner@example.test',EMAIL_ENABLED:'true',EMAIL_FROM:'login@example.test',STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_PRICE_ID:'price_old'},serviceBindings:{EMAIL:{name:'personal-mail',entrypoint:'Mailer'}},outboundService:async r=>{if(new URL(r.url).hostname==='api.stripe.com'){actualStripe++;if(!actualHosted)throw Error('Personal selfhost must not call a provider');const u=new URL(r.url),fields=new URLSearchParams(await r.text());if(u.pathname==='/v1/subscriptions'&&r.method==='GET'){const customer=u.searchParams.get('customer');return Response.json({data:actualSubscriptions.has(customer)?[structuredClone(actualSubscriptions.get(customer))]:[],has_more:false});}if(u.pathname==='/v1/billing_portal/sessions'){actualPortals.push(Object.fromEntries(fields));return Response.json({id:'bps_actual',customer:fields.get('customer'),url:'https://billing.stripe.com/p/session/actual'});}if(u.pathname.startsWith('/v1/subscriptions/')&&r.method==='POST'){const sub=[...actualSubscriptions.values()].find(x=>x.id===u.pathname.split('/').pop());assert.ok(sub);sub.cancel_at_period_end=fields.get('cancel_at_period_end')==='true';return Response.json(structuredClone(sub));}throw new Error(`unexpected actual Worker Stripe request ${r.method} ${u.pathname}`);}throw Error(`Unexpected personal selfhost outbound ${r.url}`); }},{name:'personal-mail',modules:true,compatibilityDate:'2026-10-01',script:`import {WorkerEntrypoint} from 'cloudflare:workers';export class Mailer extends WorkerEntrypoint{async send(m){return {messageId:'test-only'};}}export default{fetch(){return new Response('404',{status:404})}};`}]}));
 try{
  const realDb=await actual.getD1Database('DB');for(const migration of ['0001.sql','0002.sql','0003.sql','0004.sql','0005.sql','0006.sql','0007.sql','0008.sql','0009.sql','0010.sql'])await realDb.exec((await readFile(new URL(`migrations/${migration}`,root),'utf8')).replaceAll('\n',' '));
  const tokens={owner:'a'.repeat(64),other:'b'.repeat(64)};for(const [id,email] of [['owner','owner@example.test'],['other','other@example.test']]){await realDb.prepare('INSERT INTO accounts(id,identity_key,email,name,created_at) VALUES(?,?,?,?,?)').bind(id,id,email,id,Math.floor(Date.now()/1000)).run();await realDb.prepare("INSERT INTO sessions(token_hash,account_id,kind,name,csrf,expires_at) VALUES(?,?,'device','fixture','',?)").bind(createHash('sha256').update(tokens[id]).digest('hex'),id,Math.floor(Date.now()/1000)+3600).run();await realDb.prepare('INSERT INTO documents(account_id,updated_at) VALUES(?,?)').bind(id,Math.floor(Date.now()/1000)).run();}
  const mainReq=async(id,path,method='GET',data,status=200)=>{const r=await actual.dispatchFetch('https://personal.example.test'+path,{method,headers:{authorization:`Bearer ${tokens[id]}`,'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await r.json();transcript.push({scenario:'actual-personal-selfhost',actor:id,path,method,status:r.status,result});assert.equal(r.status,status,JSON.stringify(result));return result;};
  assert.equal((await mainReq('owner','/v1/billing')).active,true);await mainReq('owner','/v1/document','PUT',{revision:0,content:'Personal notes stay mine'});assert.equal((await mainReq('owner','/v1/document')).content,'Personal notes stay mine');await mainReq('other','/v1/document','GET',undefined,402);await mainReq('owner','/v1/teams','GET',undefined,402);await mainReq('owner','/v1/auth/start','POST',{email:'other@example.test',name:'Other computer',code_challenge:createHash('sha256').update('proof').digest('base64url')},403);
  await realDb.prepare('UPDATE accounts SET closing_at=? WHERE id=?').bind(Math.floor(Date.now()/1000),'owner').run();await mainReq('owner','/v1/document','GET',undefined,402);assert.equal(actualStripe,0);assert.equal((await realDb.prepare("SELECT content FROM documents WHERE account_id='owner'").first()).content,'Personal notes stay mine');
  pass('actual Worker personal selfhosting permits only configured owner, rejects teams/alternate email/closing access and calls no Stripe');
  const hostedToken='c'.repeat(64),hostedOwner='hosted-owner',teamId='team-actual-worker',end=Math.floor(Date.now()/1000)+31536000;
  tokens.hostedOwner=hostedToken;
  await realDb.prepare('INSERT INTO accounts(id,identity_key,email,name,customer_id,created_at) VALUES(?,?,?,?,?,?)').bind(hostedOwner,hostedOwner,'hosted@example.test',hostedOwner,'cus_personal_actual',Math.floor(Date.now()/1000)).run();
  await realDb.prepare("INSERT INTO sessions(token_hash,account_id,kind,name,csrf,expires_at) VALUES(?,?,'device','fixture','',?)").bind(createHash('sha256').update(hostedToken).digest('hex'),hostedOwner,Math.floor(Date.now()/1000)+3600).run();
  await realDb.prepare('INSERT INTO teams(id,name,legal_entity,terms_version,accepted_by,accepted_at,deployment,customer_id,subscription_id,capacity,period_end,next_capacity,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(teamId,'Actual team','Example LLC','terms-v1',hostedOwner,Math.floor(Date.now()/1000),'hosted','cus_team_actual','sub_team_actual',1,end,1,Math.floor(Date.now()/1000)).run();
  await realDb.prepare("INSERT INTO team_members(team_id,account_id,role,joined_at) VALUES(?,?,'owner',?)").bind(teamId,hostedOwner,Math.floor(Date.now()/1000)).run();
  actualSubscriptions.set('cus_team_actual',{id:'sub_team_actual',customer:'cus_team_actual',status:'active',latest_invoice:'in_team_actual',cancel_at_period_end:false,pending_update:null,items:{data:[{id:'si_team_actual',price:{id:'price_team_actual'},quantity:1,current_period_end:end}]}});
  actualSubscriptions.set('cus_personal_actual',{id:'sub_personal_actual',customer:'cus_personal_actual',status:'active',latest_invoice:'in_personal_actual',cancel_at_period_end:false,pending_update:null,items:{data:[{id:'si_personal_actual',price:{id:'price_month'},quantity:1,current_period_end:end}]}});
  actualHosted=true;
  await actual.dispatchFetch('https://personal.example.test/__config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({SELF_HOST_MODE:null,STRIPE_TEAM_PRICE_ID:'price_team_actual',STRIPE_PRICE_ID:'price_sync',STRIPE_MONTHLY_PRICE_ID:'price_month',STRIPE_YEARLY_PRICE_ID:'price_year'})});
  const actualBase=`/v1/teams/${teamId}`;
  assert.equal((await mainReq('hostedOwner',actualBase+'/billing')).paid_seats,1);
  const actualPortal=await mainReq('hostedOwner',actualBase+'/portal','POST',{});assert.equal(actualPortal.url,'https://billing.stripe.com/p/session/actual');assert.equal(actualPortals[0].customer,'cus_team_actual');assert.equal(actualPortals[0]['flow_data[type]'],'payment_method_update');
  const actualCancel=await mainReq('hostedOwner',actualBase+'/personal-renewal/cancel','POST',{confirmation:'cancel personal renewal'});assert.equal(actualCancel.cancel_at_period_end,true);assert.equal(actualSubscriptions.get('cus_personal_actual').status,'active');assert.equal(actualSubscriptions.get('cus_personal_actual').cancel_at_period_end,true);assert.equal(actualSubscriptions.get('cus_team_actual').cancel_at_period_end,false);
  assert.equal(actualStripe>0,true);
  pass('authenticated exported Worker reconciles hosted team billing, opens direct payment-method portal and cancels only personal renewal after paid team access');
 }finally{await actual.dispose();}
 await mkdir(new URL('artifacts/team-e2e/',root),{recursive:true});await writeFile(new URL('artifacts/team-e2e/report.json',root),JSON.stringify({checks,transcript,outbound:{customers:customers.size,checkout_sessions:sessions.size,seat_operations:operations.size,portal_sessions:portals.length,emails:mail.length},billingFailureCoverage:['team owner only portal and personal renewal cancel','team membership/paid access gate','bad portal URL','personal renewal cancellation is at period end and preserves current paid term','invalid confirmation'],reproduce:'cd cloud && node tests/team-e2e.mjs'},null,2)+'\n');
}finally{await mf.dispose();await rm(temp,{recursive:true,force:true});}
