import {auth,type OAuthClientProvider,type OAuthDiscoveryState,type StoredOAuthClientInformation,type StoredOAuthTokens} from '@modelcontextprotocol/client';
import {bytes,key,publicDns,endpoint,type Env,type Owner,type Connection,type Boundary} from './mcp';
const enc=new TextEncoder(),dec=new TextDecoder('utf-8',{fatal:true});
const now=()=>Math.floor(Date.now()/1000);
export const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');
export async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))),v=>v.toString(16).padStart(2,'0')).join('');}
const fail=(status:number,error:string):never=>{throw Response.json({error},{status});};
export async function encrypt(env:Env,label:string,value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12)),data=enc.encode(JSON.stringify(value));if(data.length>65536)fail(502,'oauth_state_too_large');const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(label)},await key(env),data);return Array.from(new Uint8Array([...iv,...new Uint8Array(cipher)]),v=>v.toString(16).padStart(2,'0')).join('');}
export async function decrypt<T>(env:Env,label:string,value:string):Promise<T>{try{if(!/^[0-9a-f]{56,131128}$/.test(value)||value.length%2)throw Error();const data=Uint8Array.from(value.match(/../g)!,v=>parseInt(v,16));return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:data.slice(0,12),additionalData:enc.encode(label)},await key(env),data.slice(12))));}catch{fail(503,'oauth_credentials_unavailable');}}
function publicUrl(value:string|URL){const u=new URL(value);endpoint(u.origin+u.pathname);if(u.hash||u.username||u.password)fail(400,'public_https_endpoint_required');return u;}
type State={client?:StoredOAuthClientInformation;tokens?:StoredOAuthTokens;expires?:number;verifier?:string;discovery?:OAuthDiscoveryState;scope?:string;state?:string;authorization_url?:string};
type Saved={connection_id:string;account_id:string;payload_ciphertext:string;version:number;state_hash:string|null;expires_at:number|null;device_hash:string|null;lock_id:string|null;lock_until:number|null};
const label=(c:Connection)=>JSON.stringify(['provider-oauth',c.account_id,c.id,c.url,...(c.team_id?[c.team_id]:[])]);
async function active(env:Env,c:Connection,device?:string|null){const a=await env.DB.prepare('SELECT id FROM accounts WHERE id=? AND closing_at IS NULL').bind(c.account_id).first();if(!a)fail(409,'integration_revoked');if(c.team_id&&!await env.DB.prepare('SELECT t.id FROM teams t JOIN team_members m ON m.team_id=t.id WHERE t.id=? AND m.account_id=? AND t.closing_at IS NULL AND t.capacity>0 AND t.period_end>?').bind(c.team_id,c.account_id,now()).first())fail(409,'integration_team_access_revoked');if(device&&!await env.DB.prepare("SELECT token_hash FROM sessions WHERE account_id=? AND token_hash=? AND kind='device' AND expires_at>?").bind(c.account_id,device,now()).first())fail(409,'integration_revoked');}
async function locked<T>(env:Env,c:Connection,operation:(state:State,saved:Saved)=>Promise<T>){const lock=random(),saved=await env.DB.prepare('UPDATE mcp_provider_oauth SET lock_id=?,lock_until=? WHERE connection_id=? AND account_id=? AND (lock_until IS NULL OR lock_until<=?) RETURNING *').bind(lock,now()+20,c.id,c.account_id,now()).first<Saved>();if(!saved)fail(409,'integration_oauth_busy_or_missing');try{const state=await decrypt<State>(env,label(c),saved.payload_ciphertext);const result=await operation(state,saved);const updated=await env.DB.prepare('UPDATE mcp_provider_oauth SET payload_ciphertext=?,version=version+1,state_hash=?,expires_at=?,device_hash=?,lock_id=NULL,lock_until=NULL WHERE connection_id=? AND lock_id=? AND version=? RETURNING connection_id').bind(await encrypt(env,label(c),state),state.state?await hash(state.state):null,state.state?now()+600:null,state.state?saved.device_hash:null,c.id,lock,saved.version).first();if(!updated)fail(409,'integration_revoked');return result;}finally{await env.DB.prepare('UPDATE mcp_provider_oauth SET lock_id=NULL,lock_until=NULL WHERE connection_id=? AND lock_id=?').bind(c.id,lock).run();}}
function provider(env:Env,c:Connection,state:State,signal:AbortSignal):OAuthClientProvider{
 return {
  redirectUrl:env.ORIGIN+'/mcp/provider/callback',clientMetadataUrl:env.ORIGIN+'/mcp/client-metadata.json',
  clientMetadata:{client_name:'doin.sh',redirect_uris:[env.ORIGIN+'/mcp/provider/callback'],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:state.client?.client_secret?'client_secret_post':'none'},
  state:()=>state.state!,clientInformation:()=>state.client,saveClientInformation:(value)=>{state.client=value;},tokens:()=>state.tokens,
  saveTokens:(value)=>{if(value.token_type.toLowerCase()!=='bearer'||!/^[A-Za-z0-9._~+\/-]+=*$/.test(value.access_token)||value.access_token.length>4096)fail(502,'integration_oauth_token_invalid');state.tokens=value;state.expires=now()+Math.min(value.expires_in??300,86400);},
  redirectToAuthorization:async(value)=>{const u=publicUrl(value);await publicDns(u,signal);if(u.searchParams.get('redirect_uri')!==env.ORIGIN+'/mcp/provider/callback'||u.searchParams.get('state')!==state.state||u.searchParams.get('resource')!==c.url||u.searchParams.get('code_challenge_method')!=='S256')fail(502,'integration_oauth_authorization_invalid');state.authorization_url=u.href;},
  saveCodeVerifier:(value)=>{state.verifier=value;},codeVerifier:()=>{if(!state.verifier)fail(409,'integration_oauth_required');return state.verifier;},
  validateResourceURL:async(server,resource)=>{if(new URL(server).href!==c.url||(resource&&new URL(resource).href!==c.url))fail(502,'integration_oauth_resource_mismatch');return new URL(c.url);},
  discoveryState:()=>state.discovery,saveDiscoveryState:(value)=>{if(!value.authorizationServerMetadata?.issuer||!value.authorizationServerMetadata.token_endpoint)fail(502,'integration_oauth_discovery_required');publicUrl(value.authorizationServerUrl);publicUrl(value.authorizationServerMetadata.issuer);publicUrl(value.authorizationServerMetadata.token_endpoint);if(value.authorizationServerMetadata.authorization_endpoint)publicUrl(value.authorizationServerMetadata.authorization_endpoint);state.discovery=value;},
  invalidateCredentials:(scope)=>{if(scope==='all'||scope==='tokens'){delete state.tokens;delete state.expires;}if(scope==='all'||scope==='client')delete state.client;if(scope==='all'||scope==='verifier')delete state.verifier;if(scope==='all'||scope==='discovery')delete state.discovery;}
 };
}
async function securedAuth(env:Env,c:Connection,state:State,code?:string,iss?:string){const signal=AbortSignal.timeout(15000);try{return await auth(provider(env,c,state,signal),{serverUrl:c.url,scope:state.scope,authorizationCode:code,iss,fetchFn:async(input,init)=>{
 const request=new Request(input,init),u=publicUrl(request.url);await publicDns(u,signal);
 if(!['GET','POST'].includes(request.method))fail(502,'integration_oauth_method_invalid');
 const headers=new Headers();for(const n of ['accept','content-type']){const v=request.headers.get(n);if(v)headers.set(n,v);}
 const authorization=request.headers.get('authorization');const tokenUrl=state.discovery?.authorizationServerMetadata?.token_endpoint,registrationUrl=state.discovery?.authorizationServerMetadata?.registration_endpoint;
 if(request.method==='POST'&&u.href!==tokenUrl&&u.href!==registrationUrl)fail(502,'integration_oauth_endpoint_changed');
 if(authorization){if(u.href!==tokenUrl||!authorization.startsWith('Basic '))fail(502,'integration_oauth_credential_destination_invalid');headers.set('authorization',authorization);}
 if(request.method==='POST'&&u.href===tokenUrl){const p=new URLSearchParams(await request.clone().text());if(p.get('resource')!==c.url)fail(502,'integration_oauth_resource_mismatch');}
 await active(env,c);const response=await fetch(u,{method:request.method,headers,body:request.body,redirect:'manual',signal});if(response.status>=300&&response.status<400){await response.body?.cancel();fail(502,'integration_redirect_denied');}
 const data=await bytes(response,65536,signal);return new Response(data,{status:response.status,headers:response.headers});
 }});}catch(error){if(error instanceof Response)throw error;fail(502,'integration_oauth_failed');}}
export async function providerBearer(env:Env,c:Connection):Promise<string|undefined>{if(c.auth_type!=='oauth')return undefined;return locked(env,c,async(state)=>{await active(env,c);if(!state.tokens)fail(409,'integration_oauth_required');if((state.expires??0)<=now()+30){if(!state.tokens.refresh_token)fail(409,'integration_oauth_required');const result=await securedAuth(env,c,state);if(result!=='AUTHORIZED')fail(409,'integration_oauth_required');}return state.tokens!.access_token;});}
export async function providerOAuthRoute(request:Request,env:Env,who:Owner,boundary:Boundary):Promise<Response>{const match=/^\/v1\/mcp\/connections\/([A-Za-z0-9][A-Za-z0-9_-]{0,63})\/oauth$/.exec(new URL(request.url).pathname);if(!match)fail(404,'not_found');const c=await env.DB.prepare('SELECT * FROM mcp_connections WHERE account_id=? AND name=?').bind(who.id,match[1]).first<Connection>();if(!c)fail(404,'integration_not_found');if(request.method==='DELETE'){await env.DB.batch([env.DB.prepare('DELETE FROM mcp_provider_oauth WHERE connection_id=? AND account_id=?').bind(c.id,who.id),env.DB.prepare("UPDATE mcp_connections SET auth_type='none',token_ciphertext=NULL WHERE id=? AND account_id=?").bind(c.id,who.id)]);return Response.json({revoked:true});}
 if(request.method!=='POST')fail(405,'method_not_allowed');if(who.closing_at!==null)fail(409,'account_deletion_pending');if(!await boundary.subscribed(c.team_id??undefined))fail(402,'subscription_required');const data=await boundary.body(request,8192);if(data.scope!==undefined&&(typeof data.scope!=='string'||data.scope.length>2048||!/^[\x21\x23-\x5b\x5d-\x7e ]*$/.test(data.scope)))fail(400,'integration_oauth_scope_invalid');if(data.client_id!==undefined&&(typeof data.client_id!=='string'||!data.client_id||data.client_id.length>2048))fail(400,'integration_oauth_client_invalid');if(data.client_secret!==undefined&&(typeof data.client_secret!=='string'||data.client_secret.length>4096||!data.client_id))fail(400,'integration_oauth_client_invalid');
 const state:State={scope:data.scope,state:random(),...(data.client_id?{client:{client_id:data.client_id,...(data.client_secret?{client_secret:data.client_secret}:{})}}:{})};
 await env.DB.prepare('INSERT INTO mcp_provider_oauth(connection_id,account_id,payload_ciphertext,device_hash) VALUES(?,?,?,?) ON CONFLICT(connection_id) DO NOTHING').bind(c.id,who.id,await encrypt(env,label(c),{}),who.token_hash).run();
 return locked(env,c,async(current,saved)=>{await active(env,c,who.token_hash);for(const k of Object.keys(current))delete (current as any)[k];Object.assign(current,state);saved.device_hash=who.token_hash;const result=await securedAuth(env,c,current);if(result!=='REDIRECT'||!current.authorization_url)fail(502,'integration_oauth_authorization_invalid');await env.DB.prepare("UPDATE mcp_connections SET auth_type='oauth',token_ciphertext=NULL WHERE id=? AND account_id=?").bind(c.id,who.id).run();return Response.json({authorization_url:current.authorization_url,expires_in:600,license_team_id:c.team_id??null});});
}
export async function providerOAuthPublic(request:Request,env:Env,boundary:{paid:(accountId:string,teamId?:string)=>Promise<boolean>}):Promise<Response|null>{const u=new URL(request.url);if(u.pathname==='/mcp/client-metadata.json'&&request.method==='GET')return Response.json({client_id:env.ORIGIN+'/mcp/client-metadata.json',client_name:'doin.sh',client_uri:'https://doin.sh',redirect_uris:[env.ORIGIN+'/mcp/provider/callback'],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none'});
 if(u.pathname!=='/mcp/provider/callback')return null;if(request.method!=='GET')fail(405,'method_not_allowed');const state=u.searchParams.get('state'),code=u.searchParams.get('code');if(!state||!/^[0-9a-f]{64}$/.test(state)||!code||code.length>4096)fail(400,'integration_oauth_callback_invalid');const row=await env.DB.prepare('SELECT c.* FROM mcp_connections c JOIN mcp_provider_oauth o ON o.connection_id=c.id WHERE o.state_hash=? AND o.expires_at>?').bind(await hash(state),now()).first<Connection>();if(!row)fail(400,'integration_oauth_callback_invalid');if(!await boundary.paid(row.account_id,row.team_id??undefined))fail(402,'subscription_required');
 return locked(env,row,async(current,saved)=>{if(current.state!==state||!saved.expires_at||saved.expires_at<=now())fail(400,'integration_oauth_callback_invalid');await active(env,row,saved.device_hash);const result=await securedAuth(env,row,current,code,u.searchParams.get('iss')??undefined);if(result!=='AUTHORIZED')fail(502,'integration_oauth_failed');delete current.state;delete current.verifier;delete current.authorization_url;return new Response('<!doctype html><title>doin.sh</title><h1>Integration connected.</h1><p>Return to your doin terminal.</p>',{headers:{'content-type':'text/html; charset=utf-8'}});});
}
